# Generated by Django 4.2.5 on 2023-10-29 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guessing_game_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='random',
            new_name='randomnumber',
        ),
    ]
