# Generated by Django 4.2.5 on 2023-10-29 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guessing_game_App', '0003_rename_randomnumber_randomnumber_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='boundary',
        ),
        migrations.DeleteModel(
            name='chance',
        ),
        migrations.DeleteModel(
            name='guessed',
        ),
        migrations.DeleteModel(
            name='randomnumber_table',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
